quarkus:
  datasource:
    db-kind: mysql

  rest-client:
    CalculatorService:
      url:
      scope: jakarta.inject.Singleton

"%dev":
   quarkus:
     rest-client:
       calc-service:
         url: http://microservice-dotnet-demo-pipelines.apps.cluster-8zb24.8zb24.sandbox2273.opentlc.com
#         url: ${quarkus.mockserver.endpoint}